sudo: required
services:
  - docker

branches:
  only:
    - master
    - devel

install:
  - make build_python
  - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

script:
  - make test

