sudo: required
language: python
python:
  - "3.6"

services:
  - docker

env:
  - IS_LOCAL=false

branches:
  only:
    - master
    - devel

before_install:
  - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

install:
  - pip install wait-for-it
  - make IS_LOCAL=$IS_LOCAL build_python

script:
  - make IS_LOCAL=$IS_LOCAL test
  - docker run -d -p 9000:9000 -e IS_AUTOGEN_CERT="true" iconloop/prep-node:$(make version)
  - docker ps -a
  - travis_wait 60 curl 127.0.0.1:9000/api/v1/status/peer
  - wait-for-it --service 127.0.0.1:9000 -t 200  -- curl 127.0.0.1:9000/api/v1/status/peer

