version: '3'
services:
   prep:
      image: iconloop/prep-node
      container_name: "prep-node"
      network_mode: host
      environment:
         LOOPCHAIN_LOG_LEVEL: "DEBUG"
         LOCAL_TEST: "true"
         LOG_OUTPUT_TYPE: "file"
      cap_add:
         - SYS_TIME
      volumes:
         - ./data:/data
         - ./cert:/cert # Automatically generate cert key files here
      ports:
         - 9000:9000
         - 7100:7100
