version: '3'
services:
   prep:
      image: jinwoo/python37
      container_name: "password_test"
      network_mode: host
      entrypoint: "/src/password_check.sh"
      environment:
         LOOPCHAIN_LOG_LEVEL: "DEBUG"
         LOCAL_TEST: "true"
         LOG_OUTPUT_TYPE: "file"
         PRIVATE_PASSWORD: "icon1<><><>"
         PRIVATE_PATH: "/cert/password_test2.pem"
      volumes:
         - ./src:/src
         - ./cert:/cert # Automatically generate cert key files here


